### PR TITLE
Update AWS Fargate comparison

### PR DESCRIPTION
**Pull request by ofiliz**
Thanks for writing this FAQ. A few minor corrections for Fargate:
1) Fargate doesn't require customers to manage their clusters. The cluster object (admittedly a misnomer) in Fargate does not correspond to any real compute infrastructure to be managed. It is just a way to logically separate your tasks, kind of similar to Kubernetes namespaces. You get a default one and creating a new one is completely optional. There is nothing to manage.
2) Fargate can also optionally give a free publicly accessible endpoint.
3) Fargate can also auto-scale to any custom metric defined by the customer, not just CPU and memory.

### CODE REVIEW

**Comment by ahmetb** [comment]
I think this is lgtm.
cc: @steren as fyi to review later.

**Comment by ofiliz** [comment]
Thanks.

**Comment by steren** [comment]
I am concerned that the proposed change completely removes ECS from the picture. Any reason you did so?

**Comment by ahmetb** [comment]
@ofiliz specifically, I also just noticed that there seems to be an ECS dependency (in terms of choosing a cluster) here:

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_GetStarted_Fargate.html#first-run-cluster

Is it a requirement to have an ECS cluster to use Fargate? If that's the case, we should add this part back.

**Comment by ofiliz** [comment]
No, you don't need to create an ECS cluster or any EC2 instances to use Fargate.

A Fargate cluster is a logical concept. Think a Kubernetes namespace, not a group of EC2 instances. When you use Fargate for the first time, a default cluster is automatically created for you, just like Kubernetes creates a default namespace for you. If you want to create new clusters (namespaces) to logically separate your tasks (pods), you can, but that's both optional and does not require you to manage any compute infrastructure.

This is what the UI mentioned in the link Ahmet shared above looks like. The default is pre-populated, you just click "next".
fargate

Admittedly we need to do a better job of explaining this in our documentation.

**Comment by ahmetb** [comment]
I think Fargate and Cloud Run is not apples to apples. Despite ECS seems to be virtual cluster concept and no EC2 nodes are visible (when used through Fargate), it's still very much an infra-oriented product.

The fact that "task" instances are visible to the user, autoscaling is not turned on by default, and many infra knobs are exposed, it makes it quite different than Cloud Run. The resource model of Fargate is vastly more complicated compared to Cloud Run, with many more knobs to configure to get up and running. It exposes many infrastructure details to the user, such as:

- choosing subnets, VPCs
- configuring a load balancer, and which type of LB to use
- service discovery (albeit optional)
- health checks
- autoscaling (not enabled by default), user has to configure, which is nontrivial

Below are some screenshots from my journey, I'll be making a PR to update the section with my observations.

image
image
image
image

**Comment by ofiliz** [comment]
>> I think Fargate and Cloud Run is not an apples to apples comparison.
Yes, agreed. I don't think anybody made that claim. These two products have different requirements, addressing different audiences.

The only reason I've sent this PR was to correct inaccuracies in the original FAQ, such as "you [customer] are in charge of managing your cluster", "autoscaling is CPU/memory based" and "more suitable for containers that can be long-running". Fargate customers do not manage clusters, use autoscaling based on any custom metric, and run container lifetimes ranging from a few milliseconds to several months.

The differences you have listed in your observations above aren't necessarily good or bad, they are just different because the two products have very different goals. There are trade-offs. Fargate has more knobs, but is much more useful, flexible and addresses a much wider audience. It is all fair feedback as long as you emphasize that. :)

Thanks again for writing this FAQ!

**Pull request merged**
