### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by simonw**

### CODE REVIEW

**Comment by ahmetb** [comment]
need to update the ToC as well :D

**Comment by simonw** [comment]
Oh I thought the TOC was updated automatically! I guess I need to
run that npm command. I'll try that now.

**Comment by simonw** [comment]
Inspired by your usage of markdown-toc I've added it to my https://github.com/dogsheep/twitter-to-sqlite repository and wrote a GitHub Action that runs it automatically if anything has changed. I wrote up that trick here: https://github.com/simonw/til/blob/master/github-actions/markdown-table-of-contents.md

**Comment by ahmetb** [comment]
Very interesting! So it updates the repo automatically by fixing the ToC? Do you need to give it secrets/permissions?

**Comment by simonw** [comment]
Impressively you don't - GitHub Actions automatically set up an authenticated git session that can post back to the repository. And that repo gets a special key which means any pushes it makes DON'T trigger further runs of any actions, which is exactly what I want (to avoid an infinite loop)

**Pull request merged**
