### PR TITLE
Add self-rolled warmup

### PR DESCRIPTION
**Pull request by grayside**
Notes the use of Scheduler & Tasks to build a simple warmup mechanism.

### CODE REVIEW

**Comment by ahmetb** [comment]
thanks for the PR!

I think we probably shouldn't mention the alpha thingy as it's not possible to use without whitelisting –and doesn't have CLI/UI.

I recommend simply rewriting this as:

> If you want to keep your Cloud Run services warm, configure regular invocation from Cloud Scheduler every few minutes.

What do you think?

**Comment by ahmetb** [comment]
Maybe this should be a new section called `How can I work around cold starts?` or `How can I keep my Cloud Run services “warm”?` where we basically say configure a Cloud Scheduler job that calls your service every minute?

**Comment by grayside** [comment]
Ok with that change. We can add Tasks back on alpha graduation.

**Comment by ahmetb** [comment]
updated a bit, PTAL when you have time.

**Pull request merged**
